config/routes.rb
#encoding: UTF-8
Homospiritus::Application.routes.draw do
  # Admin
  mount_activeadmin_settings
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config



  # users auth
  devise_for :users


  # registration
  get '/seminar-registration/:id', :to => 'users#seminar_registration', as: 'seminar_registration'


  # About Us
  root :to => 'about#dvizhenie'
  get '/krug-very',           :to => 'about#krug_very',   as: 'krug_very'
  get '/kto-my-i-zachem_my',  :to => 'about#kto_my',      as: 'kto_my'
  get '/stil-zhizni',         :to => 'about#stil_zhizni', as: 'stil_zhizni'



  # Activity
  get '/nashy-seminary',          :to => 'activity#nashy_seminary',           as: 'nashy_seminary'
  get '/struktury-mediator-grup', :to => 'activity#struktury_mediator_grup',  as: 'struktury_mediator_grup'
  get '/online',                  :to => 'activity#online',                   as: 'online'
  get '/utrennie-meditacyi',      :to => 'activity#utrennie_meditacyi',       as: 'utrennie_meditacyi'
  get '/shkola-vedushih',         :to => 'activity#shkola_vedushih',          as: 'shkola_vedushih'
  get '/master-voplosheniya',     :to => 'activity#master_voplosheniya',      as: 'master_voplosheniya'
  get '/gotov-k-perehodu',        :to => 'activity#gotov_k_perehodu',         as: 'gotov_k_perehodu'
  get '/zvezdnaya-polovinka',     :to => 'activity#zvezdnaya_polovinka',      as: 'zvezdnaya_polovinka'
  get '/rasspisanie',             :to => 'activity#schedule',                 as: 'rasspisanie'

  # Cooperation
  get '/sotrudnichestvo',                       :to => 'cooperation#sotrudnichestvo',         as: 'sotrudnichestvo'
  get '/fondi',                                 :to => 'cooperation#fondi',                   as: 'fondi'
  get '/predlozheniya-dlya-firm',               :to => 'cooperation#dlya_firm',               as: 'predlozheniya_dlya_firm'
  get '/predlozheniya-dlya-vedushih-seminarov', :to => 'cooperation#dlya_vedushih_seminarov', as: 'predlozheniya_dlya_vedushih_seminarov'


  get '/discussions', :to => 'discussions#index'



  # Blog
  mount_blog_at '/blog'

  get '/utro',              :to => 'articles#utro',               as: 'utro'
  get '/reshenie_problemi', :to => 'articles#reshenie_problemi',  as: 'reshenie_problemi'
  get '/usilenie',          :to => 'articles#usilenie',           as: 'usilenie'
  get '/na_noch',           :to => 'articles#na_noch',            as: 'na_noch'



end

app/views/shared/_footer.html.erb
<footer class='row'>
  <div class='twelve columns'>
    <div class='copyright'>© 2013 Движение «Стиль жизни – Любовь»</div>
  </div>
</footer>

<!--
              <li><h6>Наши контакты</h6></li>
              <li><a class="skype" href="skype:<%= settings_value 'Skype' %>?call"><%= settings_value 'Skype' %></a></li>
              <li><a class="email" href="mailto:<%= settings_value 'Email' %>"><%= settings_value 'Email' %></a></li>
-->

app/views/shared/_header.html.erb
    <nav class="top-bar">
        <ul>
          <li class="name">
            <!-- <%= link_to('/') do %>
              <%= image_tag 'homospiritus-logo-small.png', alt: 'Homo Spiritus', style: 'padding:0 10px;' %>
            <% end %> -->
            <h1><%= link_to '«Стиль жизни – Любовь»', '/' %></h1>
          </li>
          <li class="toggle-topbar"><a href="#"></a></li>
        </ul>
        <section>
          <ul class="left">
            <li class="divider show-for-medium-and-up"></li>
            
            <li class="has-dropdown">
              <!-- <a href="#">О движении</a> -->
              <a href="#">О нас</a>

              <ul class="dropdown">
<!--
                <li><label>О нас</label></li>
                <li><%= link_to 'Движение «За Творца»', '/' %></li>
-->
                <li><%= link_to 'Кто мы и зачем мы',    kto_my_path %></li>
                <li><%= link_to 'Стиль жизни',          stil_zhizni_path %></li>
              </ul>

            </li>
            
            <li class="divider show-for-medium-and-up"></li>
            
            <li class="has-dropdown">
              <a href="#">Деятельность</a>

              <ul class="dropdown">
                <li><label>Семинары</label></li>
                <li><%= link_to 'Наши живые семинары', nashy_seminary_path %></li>
                <li><%= link_to 'Школа для ведущих', shkola_vedushih_path %></li>
                <li class="divider"></li>
                <li><label>Он-лайн мероприятия</label></li>
                <li><%= link_to 'Видео семинары он-лайн', online_path %></li>
                <li><%= link_to 'Рассписание', rasspisanie_path %></li>
                <li><%= link_to 'Ежедневные утренние медитации он-лайн', utrennie_meditacyi_path %></li>
                <li><%= link_to 'Мастер воплощения»', master_voplosheniya_path %></li>
                <li><%= link_to 'Готов ли ты к Переходу?', gotov_k_perehodu_path %></li>
                <li><%= link_to 'Звездная половинка', zvezdnaya_polovinka_path %></li>
                <li class="divider"></li>
                <li><label>Информация</label></li>
                <li><%= link_to 'Круг веры', krug_very_path %></li>
                <li><%= link_to 'Подробнее о методе', struktury_mediator_grup_path %></li>
              </ul>

            </li>
            
            <li class="divider show-for-medium-and-up"></li>
            
            <li class="has-dropdown">
              <a href="#">Материалы</a>

              <ul class="dropdown">
                <li><label>Наш блог</label></li>
                <li><%= link_to 'Все статьи', blog_path %></li>
                <li class="divider"></li>
                <li><label>Категории</label></li>
                <% @blog_categories.all.each do |c| %>
                  <li><%= link_to c.name, blog_category_path(c.slug) %>
                <% end %>
                <!--
                <li class="divider"></li>
                <li><label>Волшебные слова и инструкции</label></li>
                <li><%= link_to 'Утром', utro_path %></li>
                <li>
                  <a title='Когда ПЛОХО или необходимо РЕШИТЬ ПРОБЛЕМУ'
                     href='<%= reshenie_problemi_path%>'
                     style='line-height:1.2;'>
                    Когда ПЛОХО или<br/>необходимо РЕШИТЬ ПРОБЛЕМУ
                  </a>
                </li>
                <li>
                  <a title='Усиление себя энергией рода и космической семьи'
                     href='<%= usilenie_path %>'
                     style='line-height:1.2;'>
                    Усиление себя энергией рода и<br/>космической семьи
                  </a>
                </li>
                <li><%= link_to 'На ночь', na_noch_path %></li>
                -->
              </ul>

            </li>
            <li class="divider show-for-medium-and-up"></li>
            <li class="has-dropdown">
              <a href="#">Сотрудничество</a>

              <ul class="dropdown">
                <li><%= link_to 'Сотрудничество', sotrudnichestvo_path %></li>
                <li><%= link_to 'Фонды помощи', fondi_path %></li>
                <% if user_signed_in? %>
                  <li class="divider"></li>
                  <li><label>Предложения</label></li>
                  <li><%= link_to 'Для фирм', predlozheniya_dlya_firm_path %></li>
                  <li><%= link_to 'Для ведущих семинаров', predlozheniya_dlya_vedushih_seminarov_path %></li>
                <% end %>
              </ul>
            </li>
          </ul>
          <ul class='right'>
            <% if user_signed_in? %>
              <li><%= link_to "Профиль", edit_user_registration_path %></li>
              <li class='button-link'>
                <%= link_to "Выход", destroy_user_session_path, :method => :delete, class: 'small button' %>
              </li>
            <% else %>
              <li class='button-link'>
                <%= link_to "Вход на сайт", new_user_session_path, class: 'small button' %>
              </li>
            <% end %>
          </ul>
        </section>
    </nav>

  <% if content_for?(:header) %>
    <header>
      <div class='row'>
        <div class='twelve columns'>
          <%= yield(:header) %>
        </div>
      </div>
    </header>    
  <% end %>

app/views/shared/_registration_info.html.erb
<% if user_signed_in? %>

  <% if defined? seminar_id %>

    <% if current_user.seminars.include? seminar_id.to_s %>
      <div class="alert-box success">Вы записаны на этот семинар.</div>
    <% else %>
      <p><%= link_to 'Записаться на семинар', seminar_registration_path(seminar_id), class: 'success button' %></p>
    <% end %>


  <% end %>

<% else %>
  <div class='panel' style='text-align:center;'>
    <p>Для того, чтобы принять участие в семинарах, вам необходимо зарегистрироваться.</p>
    <p><a href="/users/sign_up" class="button">Регистрация</a></p>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class='sidebar three columns'>
  <ul class="side-nav">
    <!-- <li><h6>О движении</h6></li> -->
    <li><h6>О нас</h6></li>
    <li class="divider"></li>
    <li <% if active == 1 %>class='active'<% end %>><%= link_to 'Стиль жизни - Любовь', '/' %></li>
    <li <% if active == 2 %>class='active'<% end %>><%= link_to 'Кто мы и зачем мы', kto_my_path %></li>
    <li <% if active == 4 %>class='active'<% end %>><%= link_to 'Стиль жизни', stil_zhizni_path %></li>
  </ul>

  <ul class="side-nav">
    <li><h6>Деятельность</h6></li>
    <li class="divider"></li>
    <li <% if active == 5 %>class='active'<% end %>><%= link_to 'Наши живые семинары', nashy_seminary_path %></li>
    <li <% if active == 14 %>class='active'<% end %>><%= link_to 'Школа для ведущих', shkola_vedushih_path %></li>
    <li <% if active == 3 %>class='active'<% end %>><%= link_to 'Круг веры',            krug_very_path %></li>
    <li <% if active == 6 %>class='active'<% end %>><%= link_to 'Подробнее о методе', struktury_mediator_grup_path %></li>
  </ul>
  <ul class="side-nav">
    <li><h6>Он-лайн семинары</h6></li>
    <li class="divider"></li>
    <li <% if active == 7 %>class='active'<% end %>><%= link_to 'Видео семинары он-лайн', online_path %></li>
    <li <% if active == 18 %>class='active'<% end %>><%= link_to 'Рассписание', rasspisanie_path %></li>
    <li <% if active == 13 %>class='active'<% end %>><%= link_to 'Ежедневные утренние медитации он-лайн', utrennie_meditacyi_path %></li>
    <li <% if active == 15 %>class='active'<% end %>><%= link_to 'Мастер воплощения', master_voplosheniya_path %></li>
    <li <% if active == 16 %>class='active'<% end %>><%= link_to 'Готов ли ты к Переходу?', gotov_k_perehodu_path %></li>
    <li <% if active == 17 %>class='active'<% end %>><%= link_to 'Звездная половинка', zvezdnaya_polovinka_path %></li>
  </ul>

  <ul class="side-nav">
    <li><h6>Материалы</h6></li>
    <li class="divider"></li>
    <li><%= link_to 'Все статьи', blog_path %></li>
  </ul>
  
  <ul class="side-nav">
    <li><h6>Сотрудничество</h6></li>
    <li class="divider"></li>
    <li <% if active == 9 %>class='active'<% end %>><%= link_to 'Для всех', sotrudnichestvo_path %></li>
    <li <% if active == 10 %>class='active'<% end %>><%= link_to 'Фонды помощи', fondi_path %></li>
    <% if user_signed_in? %>
      <li <% if active == 11 %>class='active'<% end %>><%= link_to 'Для фирм', predlozheniya_dlya_firm_path %></li>
      <li <% if active == 12 %>class='active'<% end %>><%= link_to 'Для ведущих семинаров', predlozheniya_dlya_vedushih_seminarov_path %></li>
    <% end %>
  </ul>
</div>